extraction:
  cpp:
    prepare:
      packages:
        - qt5-qmake
        - qtbase5-dev-tools
        - libfftw3-dev
	- libjpeg-dev
	- liblog4cpp5-dev
	- libpng12-dev
    configure:
      command:
      - qmake engauge.pro
    index:
      build_command:
        - make
	
